//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTool.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinTool.Resources.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert selected text to lowercase.
        /// </summary>
        public static string ConvertToLowercase {
            get {
                return ResourceManager.GetString("ConvertToLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert selected text to uppercase.
        /// </summary>
        public static string ConvertToUppercase {
            get {
                return ResourceManager.GetString("ConvertToUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        public static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast file creation.
        /// </summary>
        public static string FastFileCreation {
            get {
                return ResourceManager.GetString("FastFileCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on Windows startup.
        /// </summary>
        public static string LaunchOnStartup {
            get {
                return ResourceManager.GetString("LaunchOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file template.
        /// </summary>
        public static string NewFileTemplate {
            get {
                return ResourceManager.GetString("NewFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template for new file of &apos;Fast file creation&apos; shortcut.
        ///Filenames will have number before extension or at the end of the name if file doesn&apos;t have extension.
        ///Forbidden characters are ignored..
        /// </summary>
        public static string NewFileTemplateToolTip {
            get {
                return ResourceManager.GetString("NewFileTemplateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in cmd.
        /// </summary>
        public static string OpenFolderInCmd {
            get {
                return ResourceManager.GetString("OpenFolderInCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run selected exe-file with arguments.
        /// </summary>
        public static string RunWithArgs {
            get {
                return ResourceManager.GetString("RunWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy name of selected item (If no item is selected, the name of the open folder will be copied. If many items are selected, nothing will happen).
        /// </summary>
        public static string SelectedItemCopyName {
            get {
                return ResourceManager.GetString("SelectedItemCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to selected item (If no item is selected, the path to the open folder will be copied. If many items are selected, nothing will happen).
        /// </summary>
        public static string SelectedItemCopyPath {
            get {
                return ResourceManager.GetString("SelectedItemCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open, right click - menu.
        /// </summary>
        public static string TrayToolTip {
            get {
                return ResourceManager.GetString("TrayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinTool.
        /// </summary>
        public static string WinTool {
            get {
                return ResourceManager.GetString("WinTool", resourceCulture);
            }
        }
    }
}
