//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already running as admin but got: {0}.
        /// </summary>
        public static string AlreadyRunnningAsAdminError {
            get {
                return ResourceManager.GetString("AlreadyRunnningAsAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change file &apos;{0}&apos; properties.
        /// </summary>
        public static string ChangeFileProperiesTitle {
            get {
                return ResourceManager.GetString("ChangeFileProperiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change file properties.
        /// </summary>
        public static string ChangeFileProperties {
            get {
                return ResourceManager.GetString("ChangeFileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute command {0}: {1}.
        /// </summary>
        public static string CommandExecutionError {
            get {
                return ResourceManager.GetString("CommandExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert selected text to lowercase.
        /// </summary>
        public static string ConvertToLowercase {
            get {
                return ResourceManager.GetString("ConvertToLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert selected text to uppercase.
        /// </summary>
        public static string ConvertToUppercase {
            get {
                return ResourceManager.GetString("ConvertToUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        public static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find drive &apos;{0}&apos;..
        /// </summary>
        public static string DriveNotFound {
            get {
                return ResourceManager.GetString("DriveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortcut should start with at least one modifier (Ctrl, Shift, Alt, Win).
        /// </summary>
        public static string EditShortcutTip {
            get {
                return ResourceManager.GetString("EditShortcutTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Input Popup.
        /// </summary>
        public static string EnableSwitchLanguagePopup {
            get {
                return ResourceManager.GetString("EnableSwitchLanguagePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new shortcut.
        /// </summary>
        public static string EnterNewShortcut {
            get {
                return ResourceManager.GetString("EnterNewShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinTool. Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast file creation.
        /// </summary>
        public static string FastFileCreation {
            get {
                return ResourceManager.GetString("FastFileCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; consists only of dots.
        /// </summary>
        public static string FileConsistsOnlyOfDots {
            get {
                return ResourceManager.GetString("FileConsistsOnlyOfDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create file &apos;{0}&apos;: {1}.
        /// </summary>
        public static string FileCreationError {
            get {
                return ResourceManager.GetString("FileCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has forbidden characters.
        /// </summary>
        public static string FileHasForbiddenChars {
            get {
                return ResourceManager.GetString("FileHasForbiddenChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path &apos;{0}&apos; is invalid.
        /// </summary>
        public static string FilePathInvalid {
            get {
                return ResourceManager.GetString("FilePathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get settings: {0}.
        /// </summary>
        public static string GetSettingsError {
            get {
                return ResourceManager.GetString("GetSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Popup.
        /// </summary>
        public static string InputPopup {
            get {
                return ResourceManager.GetString("InputPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last write time.
        /// </summary>
        public static string LastWriteTime {
            get {
                return ResourceManager.GetString("LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on Windows startup.
        /// </summary>
        public static string LaunchOnStartup {
            get {
                return ResourceManager.GetString("LaunchOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string Lyrics {
            get {
                return ResourceManager.GetString("Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media tags.
        /// </summary>
        public static string MediaTags {
            get {
                return ResourceManager.GetString("MediaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open current folder in cmd.
        /// </summary>
        public static string OpenFolderInCmd {
            get {
                return ResourceManager.GetString("OpenFolderInCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drive &apos;{0}&apos; has only {1} free bytes (requested {2})..
        /// </summary>
        public static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performers.
        /// </summary>
        public static string Performers {
            get {
                return ResourceManager.GetString("Performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run WinTool as admin failed: {0}.
        /// </summary>
        public static string RunAsAdminError {
            get {
                return ResourceManager.GetString("RunAsAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &quot;{0}&quot; with arguments.
        /// </summary>
        public static string RunFormat {
            get {
                return ResourceManager.GetString("RunFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run selected exe-file with arguments.
        /// </summary>
        public static string RunWithArgs {
            get {
                return ResourceManager.GetString("RunWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file &apos;{0}&apos; properties error: {1}.
        /// </summary>
        public static string SaveFilePropertiesError {
            get {
                return ResourceManager.GetString("SaveFilePropertiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy name of selected/opened item.
        /// </summary>
        public static string SelectedItemCopyName {
            get {
                return ResourceManager.GetString("SelectedItemCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to selected/opened item.
        /// </summary>
        public static string SelectedItemCopyPath {
            get {
                return ResourceManager.GetString("SelectedItemCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set windows startup. {0}.
        /// </summary>
        public static string SetWindowsStartupError {
            get {
                return ResourceManager.GetString("SetWindowsStartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortcut is already used for &quot;{0}&quot;..
        /// </summary>
        public static string ShortcutAlreadyUsed {
            get {
                return ResourceManager.GetString("ShortcutAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open, right click - menu.
        /// </summary>
        public static string TrayToolTip {
            get {
                return ResourceManager.GetString("TrayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update settings: {0}.
        /// </summary>
        public static string UpdateSettingsError {
            get {
                return ResourceManager.GetString("UpdateSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Explorer.
        /// </summary>
        public static string WindowsExplorer {
            get {
                return ResourceManager.GetString("WindowsExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinTool.
        /// </summary>
        public static string WinTool {
            get {
                return ResourceManager.GetString("WinTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
